add the content of regularization
hsf-training/hsf-training-ml-webpage pull request #9
Opened 2020-12-28 14:06 UTC by anonymousr007

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution.

To ensure that someone gets notified, you can also click on "Request a review" and add
the suggested person.

Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact the HSF training convenors.

You may delete these instructions from your comment.

\- HSF Training
</details>

2021-05-04 15:16 UTC, klieret commented
Hi @meevans1 @anonymousr007 This PR has been hanging for quite some time. Is it still WIP (then you can mark it as a draft)?

2021-05-05 07:02 UTC, meevans1 approved these changes

2021-05-05 07:05 UTC, meevans1 requested changes

2021-05-05 07:05 UTC, meevans1 commented on _episodes/13-TensorFlow.md
> +> > ~~~
don't need this line if no code

2021-07-21 15:08 UTC, klieret commented
I feel like this addition isn't really on topic yet, because the bonus lesson is about tensorflow and the question seems to be general ML.

As there haven't been any updates recently, I will close this for now.

2021-07-21 15:08 UTC, closed without merging